# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

compression-level = 9         # compression level for module zips. between 1 and 9
enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 3             # max number of concurrent building jobs
update-prebuilts = true       # dont touch this
build-mindetach-module = true


[YouTube]
enabled = true                                                        # add 'enabled = false' key to entries to not build them
build-mode = "both"                                                   # 'both', 'apk' or 'module'
version = "auto"                                                      # 'auto', 'latest' or a custom one like '17.40.41'
exclusive-patches = false                                             # excludes all patches by default
microg-patch = "microg-support"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"
module-prop-name = "ytrv-mak-magisk"
merge-integrations = true
excluded-patches = "custom-branding-icon-afn-red custom-branding-name custom-video-buffer enable-wide-searchbar hide-cast-button hide-comment-component hide-shorts-button hide-shorts-component return-youtube-dislike translations"
included-patches = "force-premium-heading"

[Music-arm64]
enabled = false

[Music-arm]
enabled = false