# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

compression-level = 9         # compression level for module zips. between 1 and 9
enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 3             # max number of concurrent building jobs
update-prebuilts = true       # dont touch this
build-mindetach-module = true


[YouTube]
enabled = true                                                        # add 'enabled = false' key to entries to not build them
build-mode = "both"                                                   # 'both', 'apk' or 'module'
excluded-patches = "custom-branding-icon-afn-blue custom-branding-icon-revancify force-premium-heading materialyou"
included-patches = "client-spoof custom-branding-icon-afn-red custom-branding-name custom-seekbar-color custom-video-buffer custom-video-speed default-video-quality default-video-speed disable-haptic-feedback enable-external-browser enable-minimized-playback enable-old-layout enable-old-quality-layout enable-open-links-directly enable-seekbar-tapping enable-tablet-miniplayer enable-wide-searchbar header-switch hide-auto-captions hide-auto-player-popup-panels hide-autoplay-button hide-button-container hide-cast-button hide-channel-watermark hide-comment-component hide-create-button hide-crowdfunding-box hide-email-address hide-endscreen-cards hide-endscreen-overlay hide-filmstrip-overlay hide-flyout-panel hide-fullscreen-buttoncontainer hide-general-ads hide-info-cards hide-mix-playlists hide-pip-notification hide-player-captions-button hide-player-overlay-filter hide-shorts-button hide-shorts-component hide-startup-shorts-player hide-stories hide-suggested-actions hide-time-and-seekbar hide-video-ads layout-switch microg-support optimize-resource overlay-buttons remove-player-button-background return-youtube-dislike settings sponsorblock swipe-controls theme translations"
version = "auto"                                                      # 'auto', 'latest' or a custom one like '17.40.41'
exclusive-patches = false                                             # excludes all patches by default
microg-patch = "microg-support"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"
module-prop-name = "ytrv-mak-magisk"
merge-integrations = true