name: CI
on:
  workflow_dispatch:
  schedule:
    - cron: "0 16 * * *"

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Should build?
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        id: should_build
        run: ./scripts/workflow/ci.sh should_build

    outputs:
      SHOULD_BUILD: ${{ steps.should_build.outputs.SHOULD_BUILD }}

  config_check:
    runs-on: ubuntu-latest
    needs: check
    if: ${{ needs.check.outputs.SHOULD_BUILD == 1 }}
    env:
      TG_TOKEN: ${{ secrets.TG_TOKEN }}
      TG_CHAT: ${{ secrets.TG_CHAT }}
      TG_DEV: ${{ secrets.TG_DEV }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3

      - name: Installing Node
        run: npm ci

      - name: Checking Config
        run: npm run-script check

      - name: On Failure
        id: send_telegram_failure
        if: ${{ failure() }}
        run: ./scripts/workflow/ci.sh send_telegram_failure

      - name: On success
        id: config
        shell: bash
        run: echo "SHOULD_BUILD=1" >> $GITHUB_OUTPUT

    outputs:
      SHOULD_BUILD: ${{ steps.config.outputs.SHOULD_BUILD }}

  build:
    permissions: write-all
    needs: config_check
    uses: ./.github/workflows/build.yml
    if: ${{ needs.config_check.outputs.SHOULD_BUILD == 1 }}
    secrets: inherit

