name: CI
on:
  workflow_dispatch:
  schedule:
    - cron: "0 16 * * *"

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Should build?
        id: should_build
        shell: bash
        run: |
          source utils.sh
          toml_prep "$(cat config.toml)"

          is_youtube_latest() {
            v=$(toml_get "$(toml_get_table "YouTube")" "version") || version=""
            if [ "$v" = latest ]; then
              declare -r cur_yt=$(sed -n 's/.*YouTube: \(.*\)/\1/p' build.md | xargs)
              [ -z "$cur_yt" ] && return 1 # empty, fail=>dont build
              declare -r last_ver=$(get_apk_vers "https://www.apkmirror.com/uploads/?appcategory=youtube" | get_largest_ver)

              echo "current yt version: $cur_yt"
              echo "latest yt version: $last_ver"
              [ "$cur_yt" != "$last_ver" ] # test success=>build, fail=>dont build
            else
              return 1 # not experimental, dont build
            fi
          }

          is_patches_latest() {
            declare -r last_patches_url=$(wget -nv --header="Authorization: token ${{ secrets.GITHUB_TOKEN }}" -O- https://api.github.com/repos/inotia00/revanced-patches/releases/latest | json_get 'browser_download_url' | grep 'jar')
            declare -r last_patches=${last_patches_url##*/}
            cur_patches=$(sed -n 's/.*Patches: \(.*\)/\1/p' build.md | xargs)

            echo "current patches version: $cur_patches"
            echo "latest patches version: $last_patches"
            [ "$cur_patches" != "$last_patches" ] # test success=>build, fail=>dont build
          }

          if ! git checkout update; then
            echo "first time building!"
            echo "SHOULD_BUILD=1" >> $GITHUB_OUTPUT
          elif is_patches_latest || is_youtube_latest; then
            echo "build!"
            echo "SHOULD_BUILD=1" >> $GITHUB_OUTPUT
          else
            echo "dont build!"
            echo "SHOULD_BUILD=0" >> $GITHUB_OUTPUT
          fi

          git checkout main
    outputs:
      SHOULD_BUILD: ${{ steps.should_build.outputs.SHOULD_BUILD }}

  config_check:
    runs-on: ubuntu-latest
    needs: check
    if: ${{ needs.check.outputs.SHOULD_BUILD == 1 }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Checking Config
        uses: actions/setup-node@v3
      - run: npm ci
      - run: npm run build --if-present
      - run: npm run-script check
      - name: On Failure
        env:
          TG_TOKEN: ${{ secrets.TG_TOKEN }}
          TG_CHAT: ${{ secrets.TG_CHAT }}
        if: ${{ failure() }}
        shell: bash
        run: |
          ERRORS=$(<errors.log)
          POST="https://api.telegram.org/bot${TG_TOKEN}/sendMessage"
          URL="[Failed Action]($GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID)"
          MSG="*Check patches config*

          *LOG*
          ${ERRORS}

          ${URL}"

          curl -X POST --data-urlencode "parse_mode=Markdown" --data-urlencode "text=${MSG}" --data-urlencode "chat_id=${TG_CHAT}" "$POST"
          echo "SHOULD_BUILD=0" >> $GITHUB_OUTPUT
      - name: On success
        id: config
        shell: bash
        run: |
          echo "SHOULD_BUILD=1" >> $GITHUB_OUTPUT
    outputs:
      SHOULD_BUILD: ${{ steps.config.outputs.SHOULD_BUILD }}

  build:
    permissions: write-all
    needs: config_check
    uses: ./.github/workflows/build.yml
    if: ${{ needs.config_check.outputs.SHOULD_BUILD == 1 }}
    secrets: inherit
